server:
  port: 8765
spring:
  application:
    name: secured-gateway
  cloud:
    gateway:
      routes:
        - id: user-management-service
          uri: lb://USER-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: AuthorizationFilter
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/emails/**
          filters:
            - name: AuthorizationFilter
        - id: like-and-comment-service
          uri: lb://LIKE-AND-COMMENT-SERVICE
          predicates:
            - Path=/api/v1/like-comment/**
          filters:
            - name: AuthorizationFilter
        - id: follow-service
          uri: lb://FOLLOW-SERVICE
          predicates:
            - Path=/api/v1/follows/**
          filters:
            - name: AuthorizationFilter
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: AuthorizationFilter
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - name: AuthorizationFilter
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

customized-header-for-token: loggedin-username

